%This script runs the video_seq at various step sizes for the LAB histogram
%and collates their respective MOT scores

clear all;
close all;

step_size=1:40; %For user to adjust must be between 1-100
%Initialise storage
RunTime                 = zeros(size(step_size));
MOTP_store              = zeros(size(step_size));
MOTA_store              = zeros(size(step_size));
miss_ratio_store        = zeros(size(step_size));
fp_ratio_store          = zeros(size(step_size));
IDsw_ratio_store        = zeros(size(step_size));
Accum_ID_SW_store       = zeros(size(step_size));

for i=1:numel(step_size)
    disp(sprintf('Collating for step size: %d',step_size(i)));
 [ ...
    runTime ...
    frameNum_track, ...
    personNum_track, ...
    bodyL_Track, ...
    bodyT_Track, ...
    bodyW_Track, ...
    bodyH_track, ...
    assoc_cost, ...
    bbox_new ...
] = video_seq( ...
    step_size(i) ...
);

[ ...
    MOTP, ...
    MOTA, ...
    miss_ratio, ...
    fp_ratio, ...
    IDsw_ratio, ...
    Accum_ID_SW_OUT ...
] = calculate_MOT( ...
    frameNum_track, ...
    personNum_track, ...
    bodyL_Track, ...
    bodyT_Track, ...
    bodyW_Track, ...
    bodyH_track ...
);

RunTime(i)                 = runTime;
MOTP_store(i)              = MOTP;
MOTA_store(i)              = MOTA;
miss_ratio_store(i)        = miss_ratio;
fp_ratio_store(i)          = fp_ratio;
IDsw_ratio_store(i)        = IDsw_ratio;
Accum_ID_SW_store(i)       = Accum_ID_SW_OUT;

end

save('hungarian_result.mat','step_size','RunTime','MOTP_store','MOTA_store','miss_ratio_store','fp_ratio_store','IDsw_ratio_store','Accum_ID_SW_store');

figure
plot(step_size,RunTime,'*-');
title('Run Time vs Histogram step size');
xlabel('Histogram step size');
ylabel('Run Time/s')

figure
plot(step_size,Accum_ID_SW_store,'*-');
title('Number of ID switches vs Histogram step size');
xlabel('Histogram step size');
ylabel('Number of ID switches');
